export const categories = [
  { key: 'sports', label: 'Sports' },
  { key: 'technology', label: 'Technology' },
  { key: 'music', label: 'Music' },
  { key: 'movies', label: 'Movies' },
  { key: 'education', label: 'Education' },
  { key: 'science', label: 'Science' },
  { key: 'health', label: 'Health' },
  { key: 'politics', label: 'Politics' },
  { key: 'travel', label: 'Travel' },
  { key: 'food', label: 'Food' },
  { key: 'fashion', label: 'Fashion' },
  { key: 'art', label: 'Art' },
  { key: 'literature', label: 'Literature' },
  { key: 'gaming', label: 'Gaming' },
  { key: 'fitness', label: 'Fitness' },
  { key: 'history', label: 'History' },
  { key: 'nature', label: 'Nature' },
  { key: 'environment', label: 'Environment' },
  { key: 'business', label: 'Business' },
  { key: 'finance', label: 'Finance' },
  { key: 'psychology', label: 'Psychology' },
  { key: 'philosophy', label: 'Philosophy' },
  { key: 'economics', label: 'Economics' },
  { key: 'law', label: 'Law' },
  { key: 'space', label: 'Space' },
  { key: 'astrology', label: 'Astrology' },
  { key: 'parenting', label: 'Parenting' },
  { key: 'relationships', label: 'Relationships' },
  { key: 'pets', label: 'Pets' },
  { key: 'memes', label: 'Memes' },
  { key: 'cars', label: 'Cars' },
  { key: 'motorcycles', label: 'Motorcycles' },
  { key: 'bicycling', label: 'Bicycling' },
  { key: 'aviation', label: 'Aviation' },
  { key: 'real_estate', label: 'Real Estate' },
  { key: 'photography', label: 'Photography' },
  { key: 'architecture', label: 'Architecture' },
  { key: 'religion', label: 'Religion' },
  { key: 'spirituality', label: 'Spirituality' },
  { key: 'personal_finance', label: 'Personal Finance' },
  { key: 'investing', label: 'Investing' },
  { key: 'marketing', label: 'Marketing' },
  { key: 'entrepreneurship', label: 'Entrepreneurship' },
  { key: 'home_improvement', label: 'Home Improvement' },
  { key: 'DIY', label: 'DIY' },
  { key: 'gardening', label: 'Gardening' },
  { key: 'baking', label: 'Baking' },
  { key: 'recipes', label: 'Recipes' },
  { key: 'crafts', label: 'Crafts' },
  { key: 'podcasts', label: 'Podcasts' },
  { key: 'comedy', label: 'Comedy' }
];
